import io

from PIL import Image
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Image as RLImage
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from app.classes import CLASS_INFO
from app.schemas import AnalyzeResponse

RISK_LABEL = {"high": "High risk", "medium": "Medium risk", "low": "Low risk"}

DISCLAIMER = (
    "This report was generated by a demo AI model and was not trained on real clinical "
    "data. It cannot replace a medical diagnosis - please consult a dermatologist."
)


def build_pdf(image: Image.Image, result: AnalyzeResponse) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=20 * mm, bottomMargin=20 * mm)
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph("Skin Lesion AI Analysis Report (Demo)", styles["Title"]))
    story.append(Spacer(1, 6 * mm))

    thumb = image.convert("RGB").copy()
    thumb.thumbnail((300, 300))
    thumb_buffer = io.BytesIO()
    thumb.save(thumb_buffer, format="PNG")
    thumb_buffer.seek(0)
    story.append(RLImage(thumb_buffer, width=80 * mm, height=80 * mm * thumb.height / thumb.width))
    story.append(Spacer(1, 6 * mm))

    story.append(Paragraph(f"<b>Prediction:</b> {result.label}", styles["Normal"]))
    story.append(Paragraph(f"<b>Confidence:</b> {result.confidence * 100:.1f}%", styles["Normal"]))
    story.append(Paragraph(f"<b>Risk level:</b> {RISK_LABEL[result.risk_level]}", styles["Normal"]))
    story.append(Spacer(1, 4 * mm))

    prob_rows = [["Lesion class", "Probability"]]
    for code, prob in sorted(result.probabilities.items(), key=lambda kv: -kv[1]):
        prob_rows.append([f"{CLASS_INFO[code]['label']} ({code})", f"{prob * 100:.1f}%"])
    table = Table(prob_rows, colWidths=[110 * mm, 30 * mm])
    table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("BACKGROUND", (0, 0), (-1, 0), colors.whitesmoke),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
    ]))
    story.append(table)
    story.append(Spacer(1, 6 * mm))

    story.append(Paragraph("<b>Recommended actions</b>", styles["Heading3"]))
    story.append(Paragraph(result.guidance, styles["Normal"]))
    story.append(Spacer(1, 8 * mm))

    story.append(Paragraph("<b>Medical disclaimer</b>", styles["Heading4"]))
    story.append(Paragraph(DISCLAIMER, styles["Normal"]))

    doc.build(story)
    return buffer.getvalue()
